{% set name = "dice-ml" %}
{% set version = "0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dice_ml-{{ version }}.tar.gz
  sha256: 29e6bea9e4c877caa68ecdd5d981f91cc8de3b73cdad453fd7c7e000a336576d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jsonschema
    - numpy
    - pandas <2.0.0
    - scikit-learn
    - tqdm
    - raiutils >=0.4.0

test:
  imports:
    - dice_ml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/interpretml/DiCE
  summary: Generate Diverse Counterfactual Explanations for any machine learning model.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - janjagusch
    - bgalvao
