{% set name = "dice-ml" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dice_ml-{{ version }}.tar.gz
  sha256: 0c4c2cb57f2218ba324ef2931304ab42f5f685759688a5898b0eb85b7a25b97a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - h5py
    - jsonschema
    - numpy
    - pandas
    - python >=3.6
    - scikit-learn
    - tqdm

test:
  imports:
    - dice_ml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/interpretml/DiCE
  summary: Generate Diverse Counterfactual Explanations for any machine learning model.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - janjagusch
    - bgalvao
