schema_version: 1

context:
  name: dice-ml
  version: 0.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dice_ml-${{ version }}.tar.gz
  sha256: 29e6bea9e4c877caa68ecdd5d981f91cc8de3b73cdad453fd7c7e000a336576d

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - jsonschema
    - numpy
    - pandas <2.0.0
    - scikit-learn
    - tqdm
    - raiutils >=0.4.0

tests:
  - python:
      imports:
        - dice_ml
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Generate Diverse Counterfactual Explanations for any machine learning model.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/interpretml/DiCE

extra:
  recipe-maintainers:
    - rxm7706
    - janjagusch
    - bgalvao
